<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_descargarCupon</name>
   <tag></tag>
   <elementGuidId>ffe7a717-76c3-4e8f-9ff6-d2f4b50d9acc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;modal-cupon&quot;]/div/div/div[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-cupon&quot;]/div/div/div[2]/div/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
