<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_historialCursos</name>
   <tag></tag>
   <elementGuidId>cb97b7d7-995b-4eae-b222-8d53d9bc32a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mainView&quot;]/div/div[1]/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mainView&quot;]/div/div[1]/div/div[2]/div[2]/a</value>
   </webElementProperties>
</WebElementEntity>
