package util

import static com.kms.katalon.core.testdata.TestDataFactory.findTestData

import java.nio.charset.Charset
import java.text.Normalizer

public class RandomNames {

	private static final int maxName = 547
	private static final String[] NAMES = [
		'Abdelkader',
		'Abdeselam',
		'Adam',
		'Adolfo Antonio',
		'Adria',
		'Adrian',
		'Adrian Andres',
		'Africa',
		'Agustin',
		'Agustina',
		'Ahmed',
		'Aicha',
		'Aina',
		'Ainara',
		'Ainhoa',
		'Aitor',
		'Alba',
		'Albert',
		'Alberto',
		'Alejandra',
		'Alejandra  Yamile',
		'Alejandra Maria',
		'Alejandro',
		'Alex',
		'Alfonso',
		'Alfonso De Jesus',
		'Alfredo',
		'Ali',
		'Alicia',
		'Alvaro',
		'Amaia',
		'Amparo',
		'Ana',
		'Ana Belen',
		'Ana Cristina',
		'Ana Isabel',
		'Ana Isabel',
		'Ana Lucia',
		'Ana Maria',
		'Ander',
		'Andoni',
		'Andrea',
		'Andres',
		'Andres Felipe',
		'Andres Mauricio',
		'Ane',
		'Angel',
		'Angela',
		'Angela Maria',
		'Angeles',
		'Anna',
		'Antoni',
		'Antonia',
		'Antonio',
		'Antonio Jesus',
		'Antonio Jose',
		'Antonio Manuel',
		'Araceli',
		'Aritz',
		'Arnau',
		'Arnoldo De Jesus',
		'Ascension',
		'Asier',
		'Asuncion',
		'Aurora',
		'Barbara',
		'Bartolome',
		'Bayron Andres',
		'Beatriz',
		'Beatriz Elena',
		'Begona',
		'Benito',
		'Bernardo',
		'Bernardo',
		'Bibiana Del Socorro',
		'Bilal',
		'Blanca',
		'Blanca Elsy',
		'Boris Eulogio',
		'Camilo',
		'Candelaria',
		'Carla',
		'Carles',
		'Carlos',
		'Carlos Alberto',
		'Carlos Mario',
		'Carme',
		'Carmelo',
		'Carmen',
		'Carmen Delia',
		'Carmen Maria',
		'Carmen Rosa',
		'Carolina',
		'Catalina',
		'Celia',
		'Celsa',
		'Celso',
		'Cesar',
		'Cesar Ovidio',
		'Claudia Janneth',
		'Claudia Maria',
		'Clementh Fidelia',
		'Concepcion',
		'Consuelo',
		'Cristian',
		'Cristian Alberto',
		'Cristian Alejandro',
		'Cristina',
		'Cristobal',
		'Daniel',
		'Daniel Fernando',
		'David',
		'David Andres',
		'Deysy Liliana',
		'Diana Elizabeth',
		'Diana Patricia',
		'Diego',
		'Diego Adolfo',
		'Dina',
		'Dolores',
		'Dolors',
		'Domingo',
		'Dunia',
		'Edgar Augusto',
		'Edison Alberto',
		'Eduard',
		'Eduardo',
		'Edwin Alberto',
		'Edy Laura',
		'Elena',
		'Eliana Maria',
		'Eliana Patricia',
		'Elisa',
		'Elizabet Cristina',
		'Elkin Dario',
		'Elvira',
		'Emilia',
		'Emilio',
		'Encarnacion',
		'Eneko',
		'Enric',
		'Enrique',
		'Erasmo Humberto',
		'Erhimo',
		'Erica Yanet',
		'Ernesto Alonso',
		'Esperanza',
		'Esther',
		'Estibaliz',
		'Eva',
		'Eva Maria',
		'Fabio Nelson',
		'Fadma',
		'Farah',
		'Farida',
		'Fatima',
		'Fatima Sohora',
		'Felipe',
		'Felisa',
		'Felix',
		'Fernando',
		'Francesc',
		'Francisca',
		'Francisco',
		'Francisco De Jesus',
		'Francisco Javier',
		'Francisco Javier',
		'Francisco Jose',
		'Francisco Manuel',
		'Francisco Nelson',
		'Fuensanta',
		'Gabriel',
		'Gemma',
		'Gerard',
		'Gerardo Antonio',
		'Gerardo De Jesus',
		'German Dario',
		'Gilberto De Jesus',
		'Gines',
		'Gladys Yaneth',
		'Gloria',
		'Gloria Amparo',
		'Gloria Maria',
		'Gloria Patricia',
		'Gonzalo',
		'Gorka',
		'Gregorio',
		'Guadalupe',
		'Guillermo',
		'Guillermo Leon',
		'Gustavo Alberto',
		'Habiba',
		'Hamed',
		'Hassan',
		'Hector',
		'Hector Ivan',
		'Hector Nicolas',
		'Hernan Nicolas',
		'Humberto',
		'Humberto De Jesus',
		'Idoia',
		'Ignacio',
		'Igor',
		'Iker',
		'Imanol',
		'Ines',
		'Inmaculada',
		'Inaki',
		'Inigo',
		'Irati',
		'Iratxe',
		'Irene',
		'Iria',
		'Isabel',
		'Isabel Cristina',
		'Isabel Maria',
		'Ismael',
		'Itziar',
		'Ivan',
		'Ivan De Jesus',
		'Jaime',
		'Jaime Augusto',
		'Jasmin Astrid',
		'Jaume',
		'Javier',
		'Jeannette Dahiana',
		'Jessica',
		'Jessica Lorena',
		'Jesus',
		'Jesus Alberto',
		'Jesus Anibal',
		'Jesus Antonio',
		'Jesus Maria',
		'Jhavit Alexander',
		'Jhon Jairo',
		'Joan',
		'Joaquim',
		'Joaquin',
		'Joaquina',
		'Joel',
		'Johana',
		'John De Jesus',
		'John Jairo',
		'Jon',
		'Jonathan',
		'Jordi',
		'Jorge',
		'Jorge Eduardo',
		'Jorge Ivan',
		'Jose',
		'Jose Angel',
		'Jose Antonio',
		'Jose Bernardo',
		'Jose Carlos',
		'Jose Delio',
		'Jose Francisco',
		'Jose Ignacio',
		'Jose Javier',
		'Jose Juan',
		'Jose Leon',
		'Jose Luis',
		'Jose Manuel',
		'Jose Maria',
		'Jose Miguel',
		'Jose Ramon',
		'Jose Vicente',
		'Joseba',
		'Josefa',
		'Josefina',
		'Josep',
		'Josep Maria',
		'Josu',
		'Juan',
		'Juan Antonio',
		'Juan Carlos',
		'Juan Carlos',
		'Juan De La Cruz',
		'Juan Efren',
		'Juan Fernando',
		'Juan Francisco',
		'Juan Jose',
		'Juan Luis',
		'Juan Manuel',
		'Juan Maria',
		'Juan Pablo',
		'Juan Sebastian',
		'Juana',
		'Juana Maria',
		'Julen',
		'Julia',
		'Julian',
		'Julian Camilo',
		'Juliana',
		'Julio',
		'Julio Cesar',
		'Karim',
		'Karima',
		'Keily Karina',
		'Laia',
		'Laila',
		'Laura',
		'Laura Gicel',
		'Leidy Sirley',
		'Leire',
		'Leon Daniel',
		'Leonardo',
		'Leonardo Alonso',
		'Leydy Yuliet',
		'Leyre',
		'Lia Del Socorro',
		'Liliana Patricia',
		'Lina Maria',
		'Lluis',
		'Lorenzo',
		'Lucia',
		'Luis',
		'Luis Alejandro',
		'Luis Angel',
		'Luis Augusto',
		'Luis Carlos',
		'Luis Emilio',
		'Luis Fernando',
		'Luis Gabriel',
		'Luis Octavio',
		'Luisa',
		'Luisa Fernanda',
		'Luz Amparo',
		'Luz Dary',
		'Luz Maribel',
		'Luz Mila',
		'Luz Natalia',
		'Magdalena',
		'Maialen',
		'Maicol Yesid',
		'Maider',
		'Maite',
		'Malika',
		'Manuel',
		'Manuel Jesus',
		'Manuela',
		'Marc',
		'Marcos',
		'Margalida',
		'Margarita',
		'Margarita Maria',
		'Maria',
		'Maria Africa',
		'Maria Amparo',
		'Maria Angeles',
		'Maria Angustias',
		'Maria Antonia',
		'Maria Aranzazu',
		'Maria Asuncion',
		'Maria Begona',
		'Maria Candelaria',
		'Maria Carme',
		'Maria Carmen',
		'Maria Cinta',
		'Maria Concepcion',
		'Maria Cruz',
		'Maria Dolores',
		'Maria Dolors',
		'Maria Elena',
		'Maria Fatima',
		'Maria Fuencisla',
		'Maria Isabel',
		'Maria Jesus',
		'Maria Jose',
		'Maria Josefa',
		'Maria Llanos',
		'Maria Lourdes',
		'Maria Luisa',
		'Maria Luz',
		'Maria Magdalena',
		'Maria Mar',
		'Maria Mercedes',
		'Maria Nieves',
		'Maria Patricia',
		'Maria Paz',
		'Maria Pilar',
		'Maria Pino',
		'Maria Prado',
		'Maria Rocio',
		'Maria Rosa',
		'Maria Rosario',
		'Maria Sonsoles',
		'Maria Teresa',
		'Maria Victoria',
		'Mariam',
		'Mariano',
		'Maribel',
		'Mariem',
		'Marina',
		'Mario',
		'Mario De Jesus',
		'Marly Astrid',
		'Marta',
		'Marta Dolores',
		'Marta Nelly',
		'Martha Isabel',
		'Martha Ligia',
		'Martha Lucia',
		'Martha Rubiela',
		'Marti',
		'Martin',
		'Martin Alonso',
		'Martin Antonio',
		'Mauricio Alberto',
		'Merce',
		'Mercedes',
		'Michely Tatiana',
		'Miguel',
		'Miguel Angel',
		'Mikel',
		'Milagros',
		'Mimoun',
		'Mimount',
		'Mina',
		'Miquel',
		'Mireia',
		'Miren',
		'Miryan Gabriela',
		'Mohamed',
		'Mohammed',
		'Monica',
		'Monica Liliana',
		'Montserrat',
		'Mustafa',
		'Nabil',
		'Nadia',
		'Naima',
		'Natalia',
		'Natalia Andrea',
		'Natividad',
		'Nerea',
		'Nicolas',
		'Nicolas Alberto',
		'Noelia',
		'Nora',
		'Nora Estella',
		'Nuria',
		'Octavio Leon',
		'Ofelia Del Socorro',
		'Olatz',
		'Olga Cecilia',
		'Omar',
		'Omar Adolfo',
		'Oriol',
		'Orlando Antonio',
		'Orlando De Jesus',
		'Oscar',
		'Oscar Alonso',
		'Oscar Antonio',
		'Oscar De Jesus',
		'Pablo',
		'Paloma',
		'Pascual',
		'Patricia',
		'Pau',
		'Paula',
		'Paula Andrea',
		'Pedro',
		'Pedro Jose',
		'Pere',
		'Petra',
		'Pilar',
		'Pino',
		'Purificacion',
		'Rachid',
		'Rachida',
		'Rafael',
		'Rafael Angel',
		'Rafaela',
		'Rahma',
		'Ramon',
		'Ramon Ivan',
		'Ramona',
		'Raquel',
		'Raul',
		'Remedios',
		'Resfa Maria',
		'Ricardo',
		'Ricardo Arturo',
		'Roberto',
		'Rocio',
		'Rodrigo',
		'Rodrigo Alonso',
		'Roger',
		'Rosa',
		'Rosa Maria',
		'Rosario',
		'Ruben',
		'Ruben Dario',
		'Sagrario',
		'Said',
		'Saida',
		'Salma',
		'Salvador',
		'Samir',
		'Samira',
		'Samuel',
		'Sandra',
		'Sandra Juliana',
		'Sandra Lucia',
		'Sandra Milena',
		'Santiago',
		'Sara',
		'Sara Elena',
		'Sebastian',
		'Sebastian',
		'Sergi',
		'Sergio',
		'Sergio Andres',
		'Silvia',
		'Sohora',
		'Sol Beatriz',
		'Sonia',
		'Sonia Maribel',
		'Sonia Piedad',
		'Sonsoles',
		'Soraya',
		'Sufian',
		'Susana',
		'Teresa',
		'Teresita De Jesus',
		'Tomas',
		'Trinidad',
		'Unai',
		'Veronica',
		'Vicenta',
		'Vicente',
		'Victor',
		'Victor Andres',
		'Victor Manuel',
		'Victoria',
		'Walter Alejandro',
		'William Ferney',
		'Xabier',
		'Xavier',
		'Yamina',
		'Yasmina',
		'Yeidy Adriana',
		'Yeison Javier',
		'Yolanda',
		'Yolanda Disney',
		'Yuleidy Norbelly',
		'Yusef'
	];
	private static final int maxLastName = 25727;
	private static final int INDEX_LAST_NAME = 3
	private static final ArrayList<String> LIST = findTestData("Data Files/commons/Names").getAllData()

	/**
	 * 
	 * @return full name 
	 */
	public static String getFullName(){
		return "" + removerTildes(getName()) + " " + removerTildes(getLastName()) + " " + removerTildes(getLastName())
	}


	/**
	 * 
	 * @return only names
	 */
	public static String getName(){
		int ramNam = (int) (Math.random() * maxName)
		String name = NAMES[ramNam].toString()
		ArrayList<String> temporal = name.split(" ")
		return removerTildes(temporal[0].toString())
	}


	/**
	 * 
	 * @return only last names 
	 */
	public static String getLastName(){
		int ramLasNam = (int) (Math.random() * maxLastName)
		return removerTildes(LIST[ramLasNam][INDEX_LAST_NAME].toString())
	}

	/**
	 * 
	 * @param cadena
	 * @return cadena sin tildes 
	 */
	public static String removerTildes(String cadena) {
		return cadena.replace("Á", "A")
				.replace("É", "E")
				.replace("Í", "I")
				.replace("Ó", "O")
				.replace("Ú", "U")
				.replace("Ñ", "N")
				.replace("á", "a")
				.replace("é", "e")
				.replace("í", "i")
				.replace("ó", "o")
				.replace("ú", "u")
				.replace("ñ", "n")
				.replace("'", "")
	}
}
