<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_ValorInteres</name>
   <tag></tag>
   <elementGuidId>7bc6f620-0a56-42c9-93a9-8d37fb860b35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'valorInteres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>valorInteres</value>
      <webElementGuid>bc75a649-6d66-4110-b6c7-52c47cf9b467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8993f0cd-fafb-4485-8b08-cc16c9856d70</webElementGuid>
   </webElementProperties>
</WebElementEntity>
