<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_GuardarPazYSalvo</name>
   <tag></tag>
   <elementGuidId>cc7f4605-8a21-493c-b208-59dd94f1f5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>generaPazSalvo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;generaPazSalvo&quot;]/div/a</value>
   </webElementProperties>
</WebElementEntity>
