<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_table_comparendosMutas</name>
   <tag></tag>
   <elementGuidId>d1756d7d-158e-417e-ab75-72411b7021d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mainView&quot;]/div/div[2]/div[2]/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mainView&quot;]/div/div[2]/div[2]/div/div[1]</value>
   </webElementProperties>
</WebElementEntity>
