<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_busqueda</name>
   <tag></tag>
   <elementGuidId>0d49779d-061f-482e-9d41-d0cbf79f5702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txtBusqueda']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtBusqueda</value>
      <webElementGuid>b4b1dd57-323e-4194-b7b2-60f75182d67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc93d2dd-7f84-4911-9180-d8a288fcb827</webElementGuid>
   </webElementProperties>
</WebElementEntity>
