<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_continuar</name>
   <tag></tag>
   <elementGuidId>afaf647f-ccae-4f74-ab1d-36d4de37d752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@ng-click = 'kioscoController.siguientePaso()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dda7f53a-7533-4c92-a704-46f6d8669fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>kioscoController.siguientePaso()</value>
      <webElementGuid>97f5688a-a9f2-4c71-876a-0ad6a56f4e68</webElementGuid>
   </webElementProperties>
</WebElementEntity>
