<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_AdultoMayo80</name>
   <tag></tag>
   <elementGuidId>206299fa-3248-46f7-afa6-76b1dea32da7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'preferencial1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ad37a08-cbae-4fd3-ae42-e79c60d816ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preferencial1</value>
      <webElementGuid>fb6ff30d-1cda-4de2-bc70-d862d3ffb224</webElementGuid>
   </webElementProperties>
</WebElementEntity>
