<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_discapasidad</name>
   <tag></tag>
   <elementGuidId>7f4c9e29-c172-4ad2-b7f1-914f5cd6b153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'preferencial3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d13e421-84cc-4d2e-94d2-972d5134dd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preferencial3</value>
      <webElementGuid>9947d2f3-bb28-40cb-b075-f411dd86bcd7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
