<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_PazYSalvo</name>
   <tag></tag>
   <elementGuidId>bd2ee28c-9f45-411e-b5d0-770161bcebae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'servicio3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7493e51-bcbe-42bb-b37f-2d45415a1cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>servicio3</value>
      <webElementGuid>05f68c3f-fc06-41d2-bd23-62360c4701a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
