<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_Liquidacion</name>
   <tag></tag>
   <elementGuidId>7cab1090-361b-42f3-b47a-541590ce06ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'servicio2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59ace282-5fbd-4cf5-911b-42bfcc5f47df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>servicio2</value>
      <webElementGuid>8d913456-1cd6-46ac-81ac-1ff6aa14ee9b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
