<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_Embarazada</name>
   <tag></tag>
   <elementGuidId>8c49a804-2283-47b6-931c-c7580ef4d66f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'preferencial2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c4ae608-24a7-4b6c-8495-b4f1b6ed64bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preferencial2</value>
      <webElementGuid>06339df5-396a-4482-b980-d5e67e076b6d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
