<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_EstadoCuenta</name>
   <tag></tag>
   <elementGuidId>942e058d-d1d2-49b7-85cf-f8c2fb5a2486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'servicio1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed6581bb-12dc-439d-84fd-8471ec5b3e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>servicio1</value>
      <webElementGuid>dd44458e-a2aa-432b-8e05-316efc0552e3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
