<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Documento</name>
   <tag></tag>
   <elementGuidId>9b732911-9253-4c8b-9c7c-5d1ac25a12cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'nroDocumento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>934ec761-dbd8-4296-83fa-63685d911734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nroDocumento</value>
      <webElementGuid>d0d493de-2ffa-4ffa-b2f7-3f5b31573970</webElementGuid>
   </webElementProperties>
</WebElementEntity>
