<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_tipoDocumento</name>
   <tag></tag>
   <elementGuidId>83f7834a-329d-4bba-9f3e-7381d3250176</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SD-BACKOFFICE&quot;]/div[2]/div/div/div/div[1]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8c55eb1-113b-415a-a7f6-25ae7bdc1adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SD-BACKOFFICE&quot;]/div[2]/div/div/div/div[1]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/select</value>
      <webElementGuid>06bbd9e4-b8ca-48a1-a5ce-3584cc057188</webElementGuid>
   </webElementProperties>
</WebElementEntity>
