<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_siguienteCorreo</name>
   <tag></tag>
   <elementGuidId>e31d56b8-07d3-4677-a4b6-bb119cdbf7c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;identifierNext&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;identifierNext&quot;]//button</value>
      <webElementGuid>2d5b713b-147a-46a3-a00b-bee8f063e4f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
