<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_user</name>
   <tag></tag>
   <elementGuidId>58b85764-5a25-484b-b357-33d00b1a77bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'usuario']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usuario</value>
      <webElementGuid>77ec81aa-85fd-4d2c-8907-dd1995e199ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>899eb9b5-be83-4c8e-8d77-46b2787e7fab</webElementGuid>
   </webElementProperties>
</WebElementEntity>
