<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_LimpiarFiltro</name>
   <tag></tag>
   <elementGuidId>d7409b83-8fb8-4722-a082-4b1fe658aee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'botonLimpiar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdbaed1a-530e-46b5-ac21-6b9ce9a2a0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonLimpiar</value>
      <webElementGuid>27d38272-3867-46a4-bbca-088ba4b25da5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
