<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Secretaria</name>
   <tag></tag>
   <elementGuidId>4cb1968a-1196-4a49-899b-741e4a3dc8bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'selectSecretaria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectSecretaria</value>
      <webElementGuid>9a7078ac-f6f6-464e-9b7b-5e359be85078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>312ed351-5cfa-4538-af60-1e940a4aa7e5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
