<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_TipoDocumento</name>
   <tag></tag>
   <elementGuidId>cd22686a-a7ae-42ae-8cca-81a807bb98a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'selectTipo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectTipo</value>
      <webElementGuid>1b6c2b31-9e0b-436a-9300-890800408181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>005d0546-2673-406e-9c57-0aa2b4fc52d1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
