<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cerrar</name>
   <tag></tag>
   <elementGuidId>d402ffbe-a190-456d-a371-a85d702944ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@xpat = '//*[@id=&quot;modal-paz-salvo&quot;]/div/div/div[1]/button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpat</name>
      <type>Main</type>
      <value>//*[@id=&quot;modal-paz-salvo&quot;]/div/div/div[1]/button</value>
   </webElementProperties>
</WebElementEntity>
