package model.cargaArchivos.csv;



class ComparendoDTO {

	String COMCONSECUTIVO
	String COMNUMERO
	String COMFECHA
	String COMHORA
	String COMDIR
	String COMDIVIPOMUNI
	String COMLOCALIDADCOMUNA
	String COMPLACA
	String COMDIVIPOMATRI
	String COMTIPOVEHI
	String COMTIPOSER
	String COMCODIGORADIO
	String COMCODIGOMODALIDAD
	String COMCODIGOPASAJEROS
	String COMINFRACTOR
	String COMTIPODOC
	String COMNOMBRE
	String COMAPELLIDO
	String COMEDADINFRACTOR
	String COMDIRINFRACTOR
	String COMEMAIL
	String COMTELEINFRACTOR
	String COMIDCIUDAD
	String COMLICENCIA
	String COMCATEGORIA
	String COMSECREEXPIDE
	String COMFECHAVENCE
	String COMTIPOINFRAC
	String COMPLICTRANSITO
	String COMDIVIPOLICEN
	String COMIDENTIFICACION
	String COMIDTIPODOCPROP
	String COMNOMBREPROP
	String COMNOMBREEMPRESA
	String COMNITEMPRESA
	String COMTARJETAOPERACION
	String COMPPLACAAGENTE
	String COMOBSERVA
	String COMFUGA
	String COMACCI
	String COMINMOV
	String COMPATIOINMOVILIZA
	String COMDIRPATIOINMOVI
	String COMGRUANUMERO
	String COMPLACAGRUA
	String COMCONSECUTIINMOVI
	String COMIDENTIFICACIONTEST
	String COMNOMBRETESTI
	String COMDIRECRESTESTI
	String COMTELETESTIGO
	String COMVALOR
	String COMVALAD
	String COMORGANISMO
	String COMESTADOCOM
	String COMPOLCA
	String COMINFRACCION
	String COMVALINFRA
	String COMTIPODOCTUTOR
	String COMNRODOCTUTOR
	String COMNOMBRETUTOR
	String COMAPELLIDOTUTOR
	String COMFOTODETECCION
	String COMFECHANOTIFICACION
	String COMFUENTECOMPARENDO
	String COMLATITUD
	String COMLONGITUD
	String COMGRADOALCOHOL

	ComparendoDTO() {
		this.COMCONSECUTIVO = ''
		this.COMNUMERO = ''
		this.COMFECHA = ''
		this.COMHORA = ''
		this.COMDIR = ''
		this.COMDIVIPOMUNI = ''
		this.COMLOCALIDADCOMUNA = ''
		this.COMPLACA = ''
		this.COMDIVIPOMATRI = ''
		this.COMTIPOVEHI = ''
		this.COMTIPOSER = ''
		this.COMCODIGORADIO = ''
		this.COMCODIGOMODALIDAD = ''
		this.COMCODIGOPASAJEROS = ''
		this.COMINFRACTOR = ''
		this.COMTIPODOC = ''
		this.COMNOMBRE = ''
		this.COMAPELLIDO = ''
		this.COMEDADINFRACTOR = ''
		this.COMDIRINFRACTOR = ''
		this.COMEMAIL = ''
		this.COMTELEINFRACTOR = ''
		this.COMIDCIUDAD = ''
		this.COMLICENCIA = ''
		this.COMCATEGORIA = ''
		this.COMSECREEXPIDE = ''
		this.COMFECHAVENCE = ''
		this.COMTIPOINFRAC = ''
		this.COMPLICTRANSITO = ''
		this.COMDIVIPOLICEN = ''
		this.COMIDENTIFICACION = ''
		this.COMIDTIPODOCPROP = ''
		this.COMNOMBREPROP = ''
		this.COMNOMBREEMPRESA = ''
		this.COMNITEMPRESA = ''
		this.COMTARJETAOPERACION = ''
		this.COMPPLACAAGENTE = ''
		this.COMOBSERVA = ''
		this.COMFUGA = ''
		this.COMACCI = ''
		this.COMINMOV = ''
		this.COMPATIOINMOVILIZA = ''
		this.COMDIRPATIOINMOVI = ''
		this.COMGRUANUMERO = ''
		this.COMPLACAGRUA = ''
		this.COMCONSECUTIINMOVI = ''
		this.COMIDENTIFICACIONTEST = ''
		this.COMNOMBRETESTI = ''
		this.COMDIRECRESTESTI = ''
		this.COMTELETESTIGO = ''
		this.COMVALOR = ''
		this.COMVALAD = ''
		this.COMORGANISMO = ''
		this.COMESTADOCOM = ''
		this.COMPOLCA = ''
		this.COMINFRACCION = ''
		this.COMVALINFRA = ''
		this.COMTIPODOCTUTOR = ''
		this.COMNRODOCTUTOR = ''
		this.COMNOMBRETUTOR = ''
		this.COMAPELLIDOTUTOR = ''
		this.COMFOTODETECCION = ''
		this.COMFECHANOTIFICACION = ''
		this.COMFUENTECOMPARENDO = ''
		this.COMLATITUD = ''
		this.COMLONGITUD = ''
		this.COMGRADOALCOHOL = ''
	}
}
