<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Request 1</name>
   <tag></tag>
   <elementGuidId>5e95a39e-caf1-400e-af29-38caf4af758b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>text/xml; charset=utf-8</value>
      <webElementGuid>6a7ab5c6-0ec4-4492-aa8c-fc46466f1a6b</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.3.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <restRequestMethod></restRequestMethod>
   <restUrl></restUrl>
   <serviceType>SOAP</serviceType>
   <soapBody>&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:web=&quot;http://webservices.qxmultas.quipux.com.co&quot; xmlns:xsd=&quot;http://webservices.qxmultas.quipux.com.co/xsd&quot;>
   &lt;soapenv:Header/>
   &lt;soapenv:Body>
      &lt;web:cargaArchivoResolucion>
         &lt;!--Optional:-->
         &lt;web:resolucion>
            &lt;!--Optional:-->
            &lt;xsd:apellido>?&lt;/xsd:apellido>
            &lt;!--Optional:-->
            &lt;xsd:apellidoTutor>?&lt;/xsd:apellidoTutor>
            &lt;!--Optional:-->
            &lt;xsd:clave>?&lt;/xsd:clave>
            &lt;!--Optional:-->
            &lt;xsd:codigoI1>?&lt;/xsd:codigoI1>
            &lt;!--Optional:-->
            &lt;xsd:codigoOrganismo>?&lt;/xsd:codigoOrganismo>
            &lt;!--Optional:-->
            &lt;xsd:consecutivoR>?&lt;/xsd:consecutivoR>
            &lt;!--Optional:-->
            &lt;xsd:direccion>?&lt;/xsd:direccion>
            &lt;!--Optional:-->
            &lt;xsd:estadoResolucionPolca>?&lt;/xsd:estadoResolucionPolca>
            &lt;!--Optional:-->
            &lt;xsd:fechaComparendo>?&lt;/xsd:fechaComparendo>
            &lt;!--Optional:-->
            &lt;xsd:fechaHasta>?&lt;/xsd:fechaHasta>
            &lt;!--Optional:-->
            &lt;xsd:fechaLimitePagoCuotaAP>?&lt;/xsd:fechaLimitePagoCuotaAP>
            &lt;!--Optional:-->
            &lt;xsd:fechaNotMandamiento>?&lt;/xsd:fechaNotMandamiento>
            &lt;!--Optional:-->
            &lt;xsd:fechaResolucion>?&lt;/xsd:fechaResolucion>
            &lt;!--Optional:-->
            &lt;xsd:fotoMulta>?&lt;/xsd:fotoMulta>
            &lt;!--Optional:-->
            &lt;xsd:fuenteFotodeteccion>?&lt;/xsd:fuenteFotodeteccion>
            &lt;!--Optional:-->
            &lt;xsd:fuenteManual>?&lt;/xsd:fuenteManual>
            &lt;!--Optional:-->
            &lt;xsd:fuentePolca>?&lt;/xsd:fuentePolca>
            &lt;!--Optional:-->
            &lt;xsd:gradoAlcohol>?&lt;/xsd:gradoAlcohol>
            &lt;!--Optional:-->
            &lt;xsd:horasComunitarias>?&lt;/xsd:horasComunitarias>
            &lt;!--Optional:-->
            &lt;xsd:idCiudad>?&lt;/xsd:idCiudad>
            &lt;!--Optional:-->
            &lt;xsd:idContraventor>?&lt;/xsd:idContraventor>
            &lt;!--Optional:-->
            &lt;xsd:idTipoDocTutor>?&lt;/xsd:idTipoDocTutor>
            &lt;!--Optional:-->
            &lt;xsd:nombre>?&lt;/xsd:nombre>
            &lt;!--Optional:-->
            &lt;xsd:nombreTutor>?&lt;/xsd:nombreTutor>
            &lt;!--Optional:-->
            &lt;xsd:nroDocTutor>?&lt;/xsd:nroDocTutor>
            &lt;!--Optional:-->
            &lt;xsd:numeroComparendo>?&lt;/xsd:numeroComparendo>
            &lt;!--Optional:-->
            &lt;xsd:numeroResolucion>?&lt;/xsd:numeroResolucion>
            &lt;!--Optional:-->
            &lt;xsd:numeroResolucionAnterior>?&lt;/xsd:numeroResolucionAnterior>
            &lt;!--Optional:-->
            &lt;xsd:secretaria>?&lt;/xsd:secretaria>
            &lt;!--Optional:-->
            &lt;xsd:telefono>?&lt;/xsd:telefono>
            &lt;!--Optional:-->
            &lt;xsd:tipoD>?&lt;/xsd:tipoD>
            &lt;!--Optional:-->
            &lt;xsd:tipoR>?&lt;/xsd:tipoR>
            &lt;!--Optional:-->
            &lt;xsd:usuario>?&lt;/xsd:usuario>
            &lt;!--Optional:-->
            &lt;xsd:valorAdicionalResolucion>?&lt;/xsd:valorAdicionalResolucion>
            &lt;!--Optional:-->
            &lt;xsd:valorInfraccionResolucion1>?&lt;/xsd:valorInfraccionResolucion1>
            &lt;!--Optional:-->
            &lt;xsd:valorPagarInfraccionResolucion1>?&lt;/xsd:valorPagarInfraccionResolucion1>
            &lt;!--Optional:-->
            &lt;xsd:valorTotalResolucion>?&lt;/xsd:valorTotalResolucion>
         &lt;/web:resolucion>
      &lt;/web:cargaArchivoResolucion>
   &lt;/soapenv:Body>
&lt;/soapenv:Envelope></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod>SOAP</soapRequestMethod>
   <soapServiceEndpoint>http://wso2-simit-99777f4b-p7njq:8290/services/WsCargaArchivos.WsCargaArchivosHttpSoap11Endpoint</soapServiceEndpoint>
   <soapServiceFunction>cargaArchivoResolucion</soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>false</useServiceInfoFromWsdl>
   <wsdlAddress>file:/C:/Users/kevin.muentes/Documents/SIMIT%202.0/Soap/WsCargaArchivosSimitNuevo.xml</wsdlAddress>
</WebServiceRequestEntity>
