<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_registrar</name>
   <tag></tag>
   <elementGuidId>c22db5b4-6dc9-4d56-97ce-fa71e072f957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mainView&quot;]/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mainView&quot;]/div/div[2]/div/button</value>
      <webElementGuid>62cc12ca-08d3-4c4a-9272-31f4d1064e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Tag</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>41e2d402-a7e5-45f1-8eec-52cc10bcb7e7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
