<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_resoluciones</name>
   <tag></tag>
   <elementGuidId>72ce79e7-11fb-4c3b-bd30-a6fe59ff59f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'fileResoluciones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileResoluciones</value>
      <webElementGuid>74a2eaff-6dc7-41fb-819e-4d2133440014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20474147-a43e-45b4-8550-4ce65e27bc4e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
