<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_comparendos</name>
   <tag></tag>
   <elementGuidId>44ef68ba-04a7-4d4a-8bf6-ea731736b8fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'fileComparendos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileComparendos</value>
      <webElementGuid>29332753-2b67-4c2a-8633-b16781dc5fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32ab1225-789b-4591-892b-5a06e67e99a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
