<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_secretaria</name>
   <tag></tag>
   <elementGuidId>dfde7a57-05b2-4325-ada4-6a26696aa71a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'secretaria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secretaria</value>
      <webElementGuid>2eb6ae69-46b9-4c53-aa3a-ebfed9b546a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae4694ac-7e00-4d00-be1c-12f65db9bea7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
