<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_siguiente</name>
   <tag></tag>
   <elementGuidId>958560fc-e1aa-49f8-856d-7f94b8b6e15d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;patas&quot;]/main/article/section/form/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;patas&quot;]/main/article/section/form/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
