<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_siguiente2</name>
   <tag></tag>
   <elementGuidId>0d1f6ebe-acfa-4614-b45a-fba2bbc44e37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;patas&quot;]/main/article/section/form/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;patas&quot;]/main/article/section/form/div[2]/button[2]</value>
   </webElementProperties>
</WebElementEntity>
