<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_selecionar_sexo</name>
   <tag></tag>
   <elementGuidId>e445ef88-6f4f-4d58-8a33-eb88bcf3aab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;616079614_4051015190_label&quot;]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;616079614_4051015190_label&quot;]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
