<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_tramiteCumplido</name>
   <tag></tag>
   <elementGuidId>bf155279-2e28-4d7c-8885-b338511fba37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;616079618_4051015219_label&quot;]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;616079618_4051015219_label&quot;]/span[2]</value>
   </webElementProperties>
</WebElementEntity>
