<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_enviarCorreoCurso</name>
   <tag></tag>
   <elementGuidId>bb4d5578-1456-411e-9002-fa7e4e12dc38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//em[@id = 'curso-correo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>curso-correo</value>
   </webElementProperties>
</WebElementEntity>
