<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Request 1</name>
   <tag></tag>
   <elementGuidId>20d7400c-1201-45ef-aba2-11e87d2e44ac</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>text/xml; charset=utf-8</value>
      <webElementGuid>d520e34d-515d-4445-aa2a-9e7343cc1c2e</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.3.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <restRequestMethod></restRequestMethod>
   <restUrl></restUrl>
   <serviceType>SOAP</serviceType>
   <soapBody>&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:web=&quot;http://webservices.qxmultas.quipux.com.co&quot; xmlns:xsd=&quot;http://webservices.qxmultas.quipux.com.co/xsd&quot;>
   &lt;soapenv:Header/>
   &lt;soapenv:Body>
      &lt;web:cargaRecaudo>
         &lt;!--Optional:-->
         &lt;web:recaudo>
            &lt;!--Optional:-->
            &lt;xsd:clave>?&lt;/xsd:clave>
            &lt;!--Optional:-->
            &lt;xsd:cuenta>?&lt;/xsd:cuenta>
            &lt;!--Optional:-->
            &lt;xsd:iNIdTipoDocumento>?&lt;/xsd:iNIdTipoDocumento>
            &lt;!--Optional:-->
            &lt;xsd:iNNumeroCuota>?&lt;/xsd:iNNumeroCuota>
            &lt;!--Optional:-->
            &lt;xsd:iNcodigoCO>?&lt;/xsd:iNcodigoCO>
            &lt;!--Optional:-->
            &lt;xsd:iNconsecutivoRecaudo>?&lt;/xsd:iNconsecutivoRecaudo>
            &lt;!--Optional:-->
            &lt;xsd:iNdescripcionOrigen>?&lt;/xsd:iNdescripcionOrigen>
            &lt;!--Optional:-->
            &lt;xsd:iNestadoRecaudoPolca>?&lt;/xsd:iNestadoRecaudoPolca>
            &lt;!--Optional:-->
            &lt;xsd:iNfechaContable>?&lt;/xsd:iNfechaContable>
            &lt;!--Optional:-->
            &lt;xsd:iNfechaTransaccion>?&lt;/xsd:iNfechaTransaccion>
            &lt;!--Optional:-->
            &lt;xsd:iNhora>?&lt;/xsd:iNhora>
            &lt;!--Optional:-->
            &lt;xsd:iNidentificacion>?&lt;/xsd:iNidentificacion>
            &lt;!--Optional:-->
            &lt;xsd:iNnumeroConsignacion>?&lt;/xsd:iNnumeroConsignacion>
            &lt;!--Optional:-->
            &lt;xsd:iNnumeroReferencia>?&lt;/xsd:iNnumeroReferencia>
            &lt;!--Optional:-->
            &lt;xsd:iNsecretaria>?&lt;/xsd:iNsecretaria>
            &lt;!--Optional:-->
            &lt;xsd:iNtipoRecaudoReferencia>?&lt;/xsd:iNtipoRecaudoReferencia>
            &lt;!--Optional:-->
            &lt;xsd:iNvalorCheque>?&lt;/xsd:iNvalorCheque>
            &lt;!--Optional:-->
            &lt;xsd:iNvalorEfectivo>?&lt;/xsd:iNvalorEfectivo>
            &lt;!--Optional:-->
            &lt;xsd:iNvalorTotal>?&lt;/xsd:iNvalorTotal>
            &lt;!--Optional:-->
            &lt;xsd:interesMoroso>?&lt;/xsd:interesMoroso>
            &lt;!--Optional:-->
            &lt;xsd:secretaria>?&lt;/xsd:secretaria>
            &lt;!--Optional:-->
            &lt;xsd:usuario>?&lt;/xsd:usuario>
            &lt;!--Optional:-->
            &lt;xsd:valorAdicional>?&lt;/xsd:valorAdicional>
            &lt;!--Optional:-->
            &lt;xsd:valorDescuento>?&lt;/xsd:valorDescuento>
         &lt;/web:recaudo>
      &lt;/web:cargaRecaudo>
   &lt;/soapenv:Body>
&lt;/soapenv:Envelope></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod>SOAP</soapRequestMethod>
   <soapServiceEndpoint>http://wso2-simit-99777f4b-p7njq:8290/services/WsCargaArchivos.WsCargaArchivosHttpSoap11Endpoint</soapServiceEndpoint>
   <soapServiceFunction>cargaRecaudo</soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>false</useServiceInfoFromWsdl>
   <wsdlAddress>file:/C:/Users/kevin.muentes/Documents/SIMIT%202.0/Soap/WsCargaArchivosSimitNuevo.xml</wsdlAddress>
</WebServiceRequestEntity>
