<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_opcionModulo</name>
   <tag></tag>
   <elementGuidId>c94de160-138f-4a1d-86db-737ea18b0c38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/nav/div[4]/div[1]/ul/li[5]/ul/li[2]/a/span[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/nav/div[4]/div[1]/ul/li[5]/ul/li[2]/a/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/nav/div[4]/div[1]/ul/li[5]/ul/li[2]/a/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
</WebElementEntity>
