<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_NuevoParametro</name>
   <tag></tag>
   <elementGuidId>8cbd8400-6c16-4f3f-b7e8-dff935be2c80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'nuevoParametro']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4a91fb8-7578-4c45-a8a4-7966cd84f736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nuevoParametro</value>
      <webElementGuid>cfe94383-24ed-45cf-af7e-fac6deef9181</webElementGuid>
   </webElementProperties>
</WebElementEntity>
