<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Buscar</name>
   <tag></tag>
   <elementGuidId>77319a82-4756-4d8e-9b3b-7eb86a744b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'botonBuscar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f99854c-d020-4993-998a-c6a561edf32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>botonBuscar</value>
      <webElementGuid>3999a0ad-65a1-4de6-8e0b-fb3f1c30c072</webElementGuid>
   </webElementProperties>
</WebElementEntity>
