<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Secretaria</name>
   <tag></tag>
   <elementGuidId>a0d7236b-d12a-4d6b-bd47-9907b88a6bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'selectSecretaria']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectSecretaria</value>
      <webElementGuid>e71de39e-ee44-4d86-955f-ab6c5b1defda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>946d4ef9-1d67-4aaa-a21a-2cc912dab1d1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
